rokwire/notifications-building-block

.secrets.baseline
CHANGELOG.md
README.md
core/application.go
core/interfaces.go
core/model/common.go
core/model/firebase.go
core/model/message.go
core/model/topic.go
core/model/user.go
core/services.go
driven/firebase/adapter.go
driven/storage/adapter.go
driven/storage/collection.go
driven/storage/database.go
driver/web/auth.go
driver/web/docs/gen/def.yaml
driver/web/docs/resources/internal/v2/message.yaml
driver/web/docs/schemas/application/Message.yaml
driver/web/rest/adminapis.go
driver/web/rest/apis.go
driver/web/rest/internal.go
main.go

It covers a stable variant of the multi-tenancy feature
Resolves #76

[ID-76] Feature support multi tenancy

---

CHANGELOG.md
core/interfaces.go
core/services.go
driven/storage/adapter.go
driver/web/adapter.go
driver/web/docs/gen/def.yaml
driver/web/docs/index.yaml
driver/web/docs/resources/client/message/message-read.yaml
driver/web/rest/apis.go

API that marks unread message to read.
**Resolves #94 
- [x ] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
---
[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

[ID-94]API for marking a message as "read"

---

CHANGELOG.md
Dockerfile

Fix docs path and the Dockerfile
**Resolves #104 
---
[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

[ID-104]Fix docs path and the Dockerfile

---

CHANGELOG.md
core/services.go

[#106] Fix inappropriate store of mute and read flags which lose the original values 

---

CHANGELOG.md
core/interfaces.go
core/services.go
driven/storage/adapter.go
driver/web/adapter.go
driver/web/docs/index.yaml
driver/web/docs/resources/client/message/messages-read.yaml
driver/web/rest/apis.go

[#112] Add support of read/unread all user messages 

---

.pre-commit-config.yaml
.secrets.baseline
CHANGELOG.md
core/application.go
core/interfaces.go
core/model/message.go
core/model/user.go
core/services.go
driven/core/adapter.go
driver/web/adapter.go
driver/web/docs/gen/def.yaml
driver/web/docs/resources/bbs/mail.yaml
driver/web/docs/resources/internal/v2/message.yaml
driver/web/docs/schemas/application/Message.yaml
driver/web/rest/bbs.go
driver/web/rest/internal.go
go.mod
go.sum
main.go

_Please provide a summary of the pull request and the issue it resolves. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._
Core BB integration to allow notifications to target accounts that match arbitrary criteria.
**Resolves #97 **
[comment]: # (To select an …

[#97] send notification by account data

---

CHANGELOG.md
driven/storage/adapter.go

Find option wasn't working with Aggregate so i moved "order", "limit" and "offset" to the pipeline and now everything seems to be fine. Please take a look also and try it before i deploy.
**Resolves #120

[ID-120]Order of All Notifications 

---

core/interfaces.go
core/model/recipient.go
core/services.go
driven/storage/adapter.go
driver/web/adapter.go
driver/web/rest/adminapis.go
driver/web/rest/apis.go

[ID-126] bug get messages api returns wrong result

---

CHANGELOG.md
driven/storage/adapter.go

Fix the order filted
**Resolves #128

[ID-128]Messages are not ordered

---

CHANGELOG.md
driven/storage/adapter.go
driver/web/rest/apis.go

Fix  theGET /messages filter
**Resolves #131

[ID-131] Fix GET /messages filter

---

CHANGELOG.md
core/model/message.go
core/model/recipient.go
driven/storage/adapter.go

This PR is adding not_read_not_mute
**Resolves #133

[ID-133] Improve stats API

---

CHANGELOG.md
core/services.go

[ID-135] Add message id in the notification

---

CHANGELOG.md
core/services.go

[#137] Mute message if the global settings is set to false instead of ignoring the message 

---

CHANGELOG.md
driver/web/apis_bbs.go

[ID-141] Fix send message BBs API

---

CHANGELOG.md
core/app.go
core/app_apis_admin.go
core/interfaces.go
driven/storage/adapter.go
driven/storage/database.go
driver/web/adapter.go
driver/web/admin_permission_policy.csv
driver/web/apis_admin.go
driver/web/docs/gen/def.yaml
driver/web/docs/gen/gen_types.go
driver/web/docs/index.yaml
driver/web/docs/resources/admin/messages/stats/source.yaml
driver/web/docs/schemas/apis/admin/get-messages-stats/response/Item.yaml
driver/web/docs/schemas/apis/admin/get-messages-stats/response/Response.yaml
driver/web/docs/schemas/apis/admin/get-messages-stats/response/SentByItem.yaml
driver/web/docs/schemas/index.yaml

[ID-153] Expose messages statistics Admin API

---

CHANGELOG.md
driver/web/apis_admin.go
driver/web/docs/gen/def.yaml
driver/web/docs/gen/gen_types.go
driver/web/docs/schemas/apis/admin/get-messages-stats/response/Item.yaml

Resolves #156 
[comment]: # (If you're unsure …

[ID-156] Update the get messages stats Admin API

---

CHANGELOG.md
core/app_apis_bbs.go

[#178] Problem while deleting recipients from BB API 

---

CHANGELOG.md
Dockerfile
core/app_apis_shared.go

 [#181] Group Members receive Post Notifications even when Groups Notifications are overridden and disabled. 

---

CHANGELOG.md
Dockerfile
SECURITY.md
core/app_apis_bbs.go
core/app_apis_services.go
core/app_apis_shared.go
core/interfaces.go
core/model/message.go
core/model/user.go
driven/storage/adapter.go
driver/web/adapter.go
driver/web/apis_client.go
driver/web/docs/gen/def.yaml
driver/web/docs/index.yaml
driver/web/docs/resources/client/user-data.yaml
driver/web/docs/schemas/application/QueueItem.yaml
driver/web/docs/schemas/application/UserDataResponse.yaml
driver/web/docs/schemas/index.yaml
go.mod
go.sum

_Please provide a summary of the pull request and the issue it resolves. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._
**Resolves #(add issue number here and remove parentheses)** …

merge develop into main

---

CHANGELOG.md
Dockerfile

[ID-193] Support Google Trust Services as CA

---

CHANGELOG.md
core/app_apis_services.go
core/interfaces.go
driven/storage/adapter.go

[ID-180] Wrong unread messages count is returned by messages/stats API

---

CHANGELOG.md
core/app_queue.go
driven/storage/collection.go
driven/storage/database.go

[ID-205] Notifications queue imrovements
